# setup simulation times and time steps
begin <- 2017
end <- 2066
timeStep <- 1

# create stocks vector with initial values. Inflows and outflows
# can increase or decrease the stock's value over time
stocks  <- c(sPopulation = 25900000,
             sGeneralPractitioners <- 36490,
             sPatientsBeingTreated <- 147934232,
             sExpectedRetirement <- 912.25,
             sPopulation0_14 <- 1000000 
             sPopulation15_39 <- 1500000
             sPopulation40_64 <- 2000000
             sPopulation65_plus <- 500000

 
)
# create exogenous vector
auxs    <- c(aCrudeBirthRate = 12.6 / 1000,    
             aCrudeDeathRate = 6.3 / 1000,    
             aAverageGPVisits = 6.5,          
             aStandardGPProductivity = 22,    
             aStandardGPWorkYear = 250,       
             aTargetCompletionTime = 1,
             aAverageGPCareerDuration = 40,
             aCrudefNetOverseasMigrationRate = 9.67 / 1000,
             aDesiredGeneralPractitionersPer1000sPopulation = 1.55 / 1000,
             aAdjustmentTime = 5,
             WorkYearFlag = 1,
             ProductivtyFlag = 1,
             DC = 3
)

